---

core:

  sleep_millis: 350

programmes:

  daily:
    type: daily-routine
    config:

      transition_times:
        morning:   [07:00:00, 08:00:00]
        evening:   [17:00:00, 18:00:00]
        bedtime_1: [21:00:00, 22:00:00]
        bedtime_2: [23:00:00, 23:59:59]

      brightness:
        ceiling: [255,  96, 32, 1]
        general: [255, 112, 40, 1]
        lantern: [255, 140, 48, 1]

      colour_temperature:
        ceiling: [153, 250, 325, 400]
        general: [153, 250, 325, 400]
        lantern: [153, 250, 325, 400]

      light_groups:
        ceiling:
          - Bedroom ceiling
          - Living room ceiling
        general:
          - Bathroom 1
          - Bathroom 2
          - Bedroom uplighter 1
          - Bedroom uplighter 2
          - Hall 1
          - Hall 2
          - Kitchen 1
          - Kitchen 2
          - Kitchen 3
          - Kitchen 4
        lantern:
          - Lantern 1
          - Lantern 2

  colourful-living-room-kitchen:
    type: colourful
    config:
      interval_time: 40
      transition_time: 20
      lights:
        - Lantern 1
        - Lantern 2
        - Kitchen 1
        - Kitchen 2
        - Kitchen 3
        - Kitchen 4

  colourful-bedroom:
    type: colourful
    config:
      interval_time: 100
      transition_time: 50
      lights:
        - Bedroom uplighter 1
        - Bedroom uplighter 2

